language: node_js
node_js: '8'

stages:
  - name: test
    if: tag IS blank
  - name: deploy
    if: branch = master AND type != pull_request

notifications:
  email: false

cache: yarn

jobs:
  include:
    - stage: test
      os: linux
      sudo: required
      env:
        - CODE_TESTS_WORKSPACE=$TRAVIS_BUILD_DIR/test/_workspace
        - CODE_TESTS_PATH=$TRAVIS_BUILD_DIR/out/test/single-workspace-tests
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - gcc-4.9-multilib
            - g++-4.9-multilib
            - zip
            - libgtk2.0-0
            - libx11-dev
            - libxkbfile-dev
            - libsecret-1-dev
      before_install:
        - export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3
        - yarn global add greenkeeper-lockfile@1
      install:
        - yarn install
      before_script:
        - greenkeeper-lockfile-update
      script:
        - exit 0
        - yarn test --silent
      after_script:
        - exit 0
        - greenkeeper-lockfile-upload
    - stage: deploy
      env:
        - BUILD_LEADER_ID=2
      install:
        - rvm get stable
        - rvm install 2.4
        - gem install github_changelog_generator
        - yarn install
      script:
        - yarn build
        - yarn global add vsce
        - yarn add --no-lockfile semantic-release@^8.2.0 semantic-release-visualstudio-marketplace-version
        - semantic-release pre
        - github_changelog_generator --no-verbose -u buehler -p typescript-hero --enhancement-labels "enhancement,feature" --include-labels "bug,enhancement,feature" --future-release $(node -p "require('./package.json').version")
      after_script:
        - yarn install --production
      after_success:
        - vsce package
        - vsce publish -p $VSCE_TOKEN
        - semantic-release post

# add as soon as multi root workspaces are available:
#- CODE_TESTS_WORKSPACE=$TRAVIS_BUILD_DIR/test/multi-root.code-workspace CODE_TESTS_PATH=$TRAVIS_BUILD_DIR/out/test/multi-root-workspace-tests

# OSX Build. which takes a billon years to complete.
# - stage: test
#   os: osx
#   sudo: false
#   env:
#     - CODE_TESTS_WORKSPACE=$TRAVIS_BUILD_DIR/test/_workspace
#     - CODE_TESTS_PATH=$TRAVIS_BUILD_DIR/out/test/single-workspace-tests
#   install:
#     - yarn install
#   script:
#     - yarn test --silent
